version: '3.8'

services:
  vite-app:
    build: .
    container_name: vite-app
    networks:
      vite-network:
        ipv4_address: 172.20.0.100  # IP fija para este contenedor
    restart: unless-stopped

networks:
  vite-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24  # Rango de la red
          gateway: 172.20.0.1    # Gateway por defecto
